# Generated by Django 5.2.8 on 2025-12-04 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
